# Generated by Django 5.1.5 on 2025-02-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=200, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notification', models.TextField()),
                ('posted_date', models.DateField(auto_now=True)),
                ('posted_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('aadhaar_number', models.CharField(max_length=19, unique=True)),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('photo', models.FileField(upload_to='')),
                ('CAMP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.FileField(upload_to='')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('COORDINATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campcoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('aadhaar_number', models.CharField(max_length=19, unique=True)),
                ('photo', models.FileField(upload_to='')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('asset', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('missing_date', models.DateField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('MEMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('photo', models.FileField(upload_to='')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('posted_time', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('EMERGENCY_TEAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emergencyteam')),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('donated', models.CharField(max_length=200)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_no', models.BigIntegerField(unique=True)),
                ('aadhaar_number', models.CharField(max_length=19, unique=True)),
                ('photo', models.FileField(upload_to='')),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=200)),
                ('donated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public')),
                ('VOLENTEER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
    ]
