# Generated by Django 5.1.5 on 2025-02-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
    ]
