# Generated by Django 5.1.5 on 2025-02-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='aadhaar_number',
            field=models.CharField(default=67, max_length=19),
            preserve_default=False,
        ),
    ]
