# Generated by Django 5.1.5 on 2025-02-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_public_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='aadhaar_number',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
