# Generated by Django 5.1.5 on 2025-03-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_public_aadhaar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_time', models.TimeField(auto_now_add=True)),
                ('PUBLIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
    ]
