# Generated by Django 5.1.5 on 2025-03-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='VOLUNTEER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='PUBLIC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.public'),
        ),
    ]
