# Generated by Django 5.1.5 on 2025-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emergencyrequest_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
