# Generated by Django 5.1.5 on 2025-03-08 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
