# Generated by Django 5.1.5 on 2025-03-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_groupchat_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='CAMP',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='VOLUNTEER',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='COORDINATOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.campcoordinator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupchat',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
            preserve_default=False,
        ),
    ]
