# Generated by Django 5.1.5 on 2025-03-08 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_groupchat_camp_remove_groupchat_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='COORDINATOR',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='CAMP',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.camp'),
            preserve_default=False,
        ),
    ]
