# Generated by Django 5.1.5 on 2025-03-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_groupchat_coordinator_groupchat_camp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='CAMP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp'),
        ),
    ]
