# Generated by Django 5.1.5 on 2025-03-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_groupchat_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='VOLENTEER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
    ]
